CREATE DATABASE QL_CAFE

USE QL_CAFE
go
CREATE TABLE VAITRO
(
	MAVT int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENVT NVARCHAR(50)
)
go
CREATE TABLE NHANVIEN
(
	MANV int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENNV NVARCHAR(50),
	EMAIL VARCHAR(50),
	SDT VARCHAR(12),
	TENDANGNHAP VARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(50) NOT NULL,
	MAVT int
)
go
ALTER TABLE NHANVIEN ADD CONSTRAINT fk_NV_VT FOREIGN KEY (MAVT) REFERENCES VAITRO(MAVT)
go
CREATE TABLE NHACUNGCAP
(
	MANCC int IDENTITY(1,1) PRIMARY KEY,
	TENNCC nvarchar(50),
	SDT varchar(15),
	DIACHI nvarchar(100)
)
CREATE TABLE NGUYENLIEU
(
	MANL int IDENTITY(1,1) PRIMARY KEY,
	TENNL nvarchar(100),
	MANCC int,
	SOLUONG int,
	CAPNHATNGAY date,
	CONSTRAINT fk_NL_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
)
CREATE TABLE LOAISANPHAM
(
	MALOAI int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENLOAI NVARCHAR(50)
)
CREATE TABLE MATHANG
(
	MAMH int IDENTITY(1,1) PRIMARY KEY,
	TENMH nvarchar(50),
	DONGIA int,
	ANH varchar(50),
	MALOAI int,
	MANL int,
	CONSTRAINT fk_LOAIMON FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI),
	CONSTRAINT fk_SP_NL FOREIGN KEY (MANL) REFERENCES NGUYENLIEU(MANL)
)

CREATE TABLE HOADON
(
	MAHD int IDENTITY(1,1) PRIMARY KEY,
	MANV int,
	NGAYLAP date,
	THANHTIEN int,
	CONSTRAINT fk_HOADONBAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
)
CREATE TABLE CHITIETHOADON
(
	MAHD int,
	MAMH int,
	SL int,
	DONGIA int,
	THANHTIEN int,
	CONSTRAINT pk_CTHD PRIMARY KEY (MAHD,MAMH),
	CONSTRAINT fk_CTHD_MH FOREIGN KEY (MAMH) REFERENCES MATHANG(MAMH),
	CONSTRAINT fk_CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
)
